catch Throwable instead of Exception. here is an example.
2015-03-02 22:50:33,070 ERROR com.netflix.chukwa.suro.SuroSinkConfigurator$1:41 [pollingConfigurationSource] [propertyChanged] reqId= Error firing configuration event
java.lang.NoClassDefFoundError: org/apache/kafka/common/serialization/Serializer